name: Signs-Subserver
version: '${project.version}'
main: de.korzhorz.signs.subserver.Main
api-version: 1.20
commands:
  maintenance:
    description: Set the maintenance mode
    usage: /maintenance <on|off|status>
    permission: maintenance
  motd:
    description: Set the MOTD
    usage: /motd <text>
    permission: motd
