name: Build with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Compile Minecraft Spigot (via BuildTools)
        uses: SpraxDev/Action-SpigotMC@v4.2.0
        with:
          versions: 1.20.1
      - name: Build with Maven
        run: 'mvn -B -Duser.name="GitHub Runner on $GITHUB_REPOSITORY (id=$GITHUB_RUN_ID)" clean package'
      - name: 'Upload Build Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: Plugin-Artifacts
          path: ./target/*.jar
